### ISSUE TITLE
Adding Code for data extraction to R

### ISSUE THREAD

**Issue by amitbend** [casras111/datahack2016#1]
As the dataset is the same for all of us,
it will be good if one of us will add to the repo a piece of code of loading the data into R as a dataframe/matrix

**Comment by casras111** [comment]
I plan to explore this tomorrow, read the indexes definitions and the paper they put on their web site with some statistics, and I can also put the loading script in the repo. The loading itself should be a single line of code, the hard work would be to define how to structure it and what to extract for the analysis. I feel that doing that before the hackaton though would not be ethical and also take some of the fun out of the exercise so I expect we'll spend the first part of Wednesday deciding together what we're after, exploring the data and munging it...

**Comment by casras111** [comment]
done
